# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.4.0

pipelines:
  default:
    - step:
        script:
                 
          # Install dependencies
          - npm install
          
          # build the proyect
          - npm run build
          
          # create the ssh folder where the private keys will be placed
          - mkdir -p ~/.ssh
          
          # The key is added
          - (umask  077 ; echo $DOO_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa)
          
          # Remove all the hmtl folder's files
          - ssh -o StrictHostKeyChecking=no doo1@157.230.189.153 rm -rf /var/www/doomicilios.net/html/*
          
          # Add the generated files
          - scp -o StrictHostKeyChecking=no -r build/* doo1@157.230.189.153:/var/www/doomicilios.net/html

