// Constantes de alertas
export enum AlertConstats {
    ALERT_SUCCESS,
    ALERT_ERROR,
    ALERT_CLEAR
};

// Constantes de usuario
export enum UserConstants {
    FACEBOOK_LOGIN_REQUEST = "FACEBOOK_LOGIN_REQUEST",
    FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    SAVE_FACEBOOK_USER = "SAVE_FACEBOOK_USER",
    FACEBOOK_USER_REGISTER_REQUEST = "FACEBOOK_USER_REGISTER_REQUEST"
};